services:
    - type: web
      name: are-we-even
      runtime: docker
      plan: free
      healthCheckPath: /
      envVars:
          - key: APP_ENV
            value: prod
          - key: APP_SECRET
            generateValue: true
          - key: DATABASE_URL
            fromDatabase:
                name: are-we-even-db
                property: connectionString
          - key: MAILER_DSN
            sync: false

databases:
    - name: are-we-even-db
      plan: free
