<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260503111745 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE expense (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, description VARCHAR(255) NOT NULL, amount NUMERIC(10, 2) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, payer_id INT NOT NULL, relation_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2D3A8DA6C17AD9A9 ON expense (payer_id)');
        $this->addSql('CREATE INDEX IDX_2D3A8DA63256915B ON expense (relation_id)');
        $this->addSql('CREATE TABLE relation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user1_id INT NOT NULL, user2_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6289474956AE248B ON relation (user1_id)');
        $this->addSql('CREATE INDEX IDX_62894749441B8B65 ON relation (user2_id)');
        $this->addSql('CREATE TABLE relation_invite (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, invitee_email VARCHAR(255) NOT NULL, token VARCHAR(255) NOT NULL, status VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, inviter_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D0C610415F37A13B ON relation_invite (token)');
        $this->addSql('CREATE INDEX IDX_D0C61041B79F4F04 ON relation_invite (inviter_id)');
        $this->addSql('CREATE TABLE reset_password_request (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, selector VARCHAR(20) NOT NULL, hashed_token VARCHAR(100) NOT NULL, requested_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7CE748AA76ED395 ON reset_password_request (user_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, last_viewed_relation_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8D93D64935B2C549 ON "user" (last_viewed_relation_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('ALTER TABLE expense ADD CONSTRAINT FK_2D3A8DA6C17AD9A9 FOREIGN KEY (payer_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE expense ADD CONSTRAINT FK_2D3A8DA63256915B FOREIGN KEY (relation_id) REFERENCES relation (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE relation ADD CONSTRAINT FK_6289474956AE248B FOREIGN KEY (user1_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE relation ADD CONSTRAINT FK_62894749441B8B65 FOREIGN KEY (user2_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE relation_invite ADD CONSTRAINT FK_D0C61041B79F4F04 FOREIGN KEY (inviter_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reset_password_request ADD CONSTRAINT FK_7CE748AA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D64935B2C549 FOREIGN KEY (last_viewed_relation_id) REFERENCES relation (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE expense DROP CONSTRAINT FK_2D3A8DA6C17AD9A9');
        $this->addSql('ALTER TABLE expense DROP CONSTRAINT FK_2D3A8DA63256915B');
        $this->addSql('ALTER TABLE relation DROP CONSTRAINT FK_6289474956AE248B');
        $this->addSql('ALTER TABLE relation DROP CONSTRAINT FK_62894749441B8B65');
        $this->addSql('ALTER TABLE relation_invite DROP CONSTRAINT FK_D0C61041B79F4F04');
        $this->addSql('ALTER TABLE reset_password_request DROP CONSTRAINT FK_7CE748AA76ED395');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D64935B2C549');
        $this->addSql('DROP TABLE expense');
        $this->addSql('DROP TABLE relation');
        $this->addSql('DROP TABLE relation_invite');
        $this->addSql('DROP TABLE reset_password_request');
        $this->addSql('DROP TABLE "user"');
    }
}
